//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ClaimDi.WCF.Insurer.BKIService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BKI_KFKSoap", Namespace="http://tempuri.org/")]
    public partial class BKI_KFK : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PolicyValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitNotifyEventOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BKI_KFK() {
            this.Url = global::ClaimDi.WCF.Insurer.Properties.Settings.Default.ClaimDi_WCF_Insurer_BKIService_BKI_KFK;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PolicyValidationCompletedEventHandler PolicyValidationCompleted;
        
        /// <remarks/>
        public event SubmitNotifyEventCompletedEventHandler SubmitNotifyEventCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PolicyValidation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KFKReqResult PolicyValidation(string car_license_no, string car_license_province, string driver_first_name, string driver_last_name, string driver_mobile_no) {
            object[] results = this.Invoke("PolicyValidation", new object[] {
                        car_license_no,
                        car_license_province,
                        driver_first_name,
                        driver_last_name,
                        driver_mobile_no});
            return ((KFKReqResult)(results[0]));
        }
        
        /// <remarks/>
        public void PolicyValidationAsync(string car_license_no, string car_license_province, string driver_first_name, string driver_last_name, string driver_mobile_no) {
            this.PolicyValidationAsync(car_license_no, car_license_province, driver_first_name, driver_last_name, driver_mobile_no, null);
        }
        
        /// <remarks/>
        public void PolicyValidationAsync(string car_license_no, string car_license_province, string driver_first_name, string driver_last_name, string driver_mobile_no, object userState) {
            if ((this.PolicyValidationOperationCompleted == null)) {
                this.PolicyValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPolicyValidationOperationCompleted);
            }
            this.InvokeAsync("PolicyValidation", new object[] {
                        car_license_no,
                        car_license_province,
                        driver_first_name,
                        driver_last_name,
                        driver_mobile_no}, this.PolicyValidationOperationCompleted, userState);
        }
        
        private void OnPolicyValidationOperationCompleted(object arg) {
            if ((this.PolicyValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PolicyValidationCompleted(this, new PolicyValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubmitNotifyEvent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public KFKNoticeeResult SubmitNotifyEvent(string xmlData) {
            object[] results = this.Invoke("SubmitNotifyEvent", new object[] {
                        xmlData});
            return ((KFKNoticeeResult)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitNotifyEventAsync(string xmlData) {
            this.SubmitNotifyEventAsync(xmlData, null);
        }
        
        /// <remarks/>
        public void SubmitNotifyEventAsync(string xmlData, object userState) {
            if ((this.SubmitNotifyEventOperationCompleted == null)) {
                this.SubmitNotifyEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitNotifyEventOperationCompleted);
            }
            this.InvokeAsync("SubmitNotifyEvent", new object[] {
                        xmlData}, this.SubmitNotifyEventOperationCompleted, userState);
        }
        
        private void OnSubmitNotifyEventOperationCompleted(object arg) {
            if ((this.SubmitNotifyEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitNotifyEventCompleted(this, new SubmitNotifyEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KFKReqResult {
        
        private Policy policyField;
        
        private Result resultField;
        
        /// <remarks/>
        public Policy policy {
            get {
                return this.policyField;
            }
            set {
                this.policyField = value;
            }
        }
        
        /// <remarks/>
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Policy {
        
        private string policy_noField;
        
        private string policy_effectiveField;
        
        private string policy_risk_noField;
        
        private string car_license_noField;
        
        private string car_license_provinceField;
        
        private string owner_first_nameField;
        
        private string owner_last_nameField;
        
        private string owner_mobile_noField;
        
        /// <remarks/>
        public string policy_no {
            get {
                return this.policy_noField;
            }
            set {
                this.policy_noField = value;
            }
        }
        
        /// <remarks/>
        public string policy_effective {
            get {
                return this.policy_effectiveField;
            }
            set {
                this.policy_effectiveField = value;
            }
        }
        
        /// <remarks/>
        public string policy_risk_no {
            get {
                return this.policy_risk_noField;
            }
            set {
                this.policy_risk_noField = value;
            }
        }
        
        /// <remarks/>
        public string car_license_no {
            get {
                return this.car_license_noField;
            }
            set {
                this.car_license_noField = value;
            }
        }
        
        /// <remarks/>
        public string car_license_province {
            get {
                return this.car_license_provinceField;
            }
            set {
                this.car_license_provinceField = value;
            }
        }
        
        /// <remarks/>
        public string owner_first_name {
            get {
                return this.owner_first_nameField;
            }
            set {
                this.owner_first_nameField = value;
            }
        }
        
        /// <remarks/>
        public string owner_last_name {
            get {
                return this.owner_last_nameField;
            }
            set {
                this.owner_last_nameField = value;
            }
        }
        
        /// <remarks/>
        public string owner_mobile_no {
            get {
                return this.owner_mobile_noField;
            }
            set {
                this.owner_mobile_noField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Notify {
        
        private string notice_noField;
        
        private string notice_datetimeField;
        
        /// <remarks/>
        public string notice_no {
            get {
                return this.notice_noField;
            }
            set {
                this.notice_noField = value;
            }
        }
        
        /// <remarks/>
        public string notice_datetime {
            get {
                return this.notice_datetimeField;
            }
            set {
                this.notice_datetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KFKNoticeeResult {
        
        private Notify notifyField;
        
        private Result resultField;
        
        /// <remarks/>
        public Notify notify {
            get {
                return this.notifyField;
            }
            set {
                this.notifyField = value;
            }
        }
        
        /// <remarks/>
        public Result result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private string successField;
        
        private string messageField;
        
        /// <remarks/>
        public string success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PolicyValidationCompletedEventHandler(object sender, PolicyValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PolicyValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PolicyValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KFKReqResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KFKReqResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SubmitNotifyEventCompletedEventHandler(object sender, SubmitNotifyEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitNotifyEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitNotifyEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KFKNoticeeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KFKNoticeeResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591